### ISSUE TITLE
can't create directory '/opt/': No such file or directory

### ISSUE THREAD

**Issue by chmarfield** [Caleb9/asuswrt-merlin-nordvpn-wg-updater#2]
I am trying to install it on my Asus RT-AX86U Pro with Merlin 3004.388.8_2. JFFS custom scripts and configs enabled.
Getting the error: "can't create directory '/opt/': No such file or directory"

#####
Asuswrt-Merlin version: 388.8
JFFS partition: enabled
Router architecture: aarch64

Enabled WireGuard NordVPN clients:
[1] wgc1 (de728.nordvpn.com)
Select client instance for recommended server [1-1, e: exit]: 1
Downloading jq-linux-arm64 into /opt/usr/bin
mkdir: can't create directory '/opt/': No such file or directory
#####
![Picture3](https://github.com/user-attachments/assets/f979eb47-0fc3-473f-8160-abf352a81af7)
![Picture2](https://github.com/user-attachments/assets/1a76c620-f497-410d-b6ff-41a1040b0488)

**Comment by Caleb9** [comment]
Try to create the directory: `mkdir -p /opt/usr/bin`.

The script probably doesn't consider a situation when `/opt` doesn't exist. I'll fix it at some point, but meanwhile please try the solution and let me know if it worked :).

**Comment by Caleb9** [comment]
Ok I checked it, you cannot create directories on the root file system. Your screenshot indicates that there is a symbolic link `opt -> tmp/opt` but for some reason the `tmp/opt` directory doesn't exist. So try to run

```
mkdir -p -m 755 /tmp/opt/usr/bin
```

and retry the installation. HTH.

**Comment by ktdt00** [comment]
> mkdir -p -m 755 /tmp/opt/usr/bin

This worked to allow the installation to complete.

**Comment by chmarfield** [comment]
Thank you. Manually creating the required folders fixed the issues and the installation competed successfully. 👍
